version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      # Install Snyk
      - echo Install Snyk
      - curl -Lo ./snyk "https://github.com/snyk/snyk/releases/download/v1.210.0/snyk-linux"
      - chmod -R +x ./snyk
      # Snyk auth
      # - ./snyk config set api="$SNYK_AUTH_TOKEN"
      # Build Docker image for testing
      - echo Build client and backend docker images for testing...
      - docker build -t sohan0077/react-test -f ./client/Dockerfile.dev ./client
      - docker build -t sohan0077/nodejs-test -f ./backend/Dockerfile.dev ./backend
  build:
    commands:
      - echo Build started on `date`
      # Run tests with built Docker images
      - echo Run react tests...
      - docker run -e CI=true sohan0077/react-test
      - echo Run nodejs tests...
      - docker run -e CI=true sohan0077/nodejs-test
      # Scan Docker image with Snyk
      ## Client
      ## Run test for security vulernabilities
      # - ./snyk test --severity-threshold=medium --docker sohan0077/react-test:latest --file=./client/Dockerfile.dev
      ## Setup continuous monitoring
      # - ./snyk monitor --docker sohan0077/react-test:latest --file=./client/Dockerfile.dev
      ## Backend
      ## Run test for security vulernabilities
      # - ./snyk test --severity-threshold=medium --docker sohan0077/nodejs-test:latest --file=./backend/Dockerfile.dev
      ## Setup continuous monitoring
      # - ./snyk monitor --docker sohan0077/nodejs-test:latest --file=./backend/Dockerfile.dev
      # Build the Docker images
      - echo Building the production Docker image...
      - docker build -t sohan0077/dkr-multicontainer-app-client ./client
      - docker build -t sohan0077/dkr-multicontainer-app-backend ./backend
      - docker build -t sohan0077/dkr-multicontainer-app-nginx ./nginx
      # Log in to the Docker CLI
      - echo "sohanhas45" | docker login -u "sohan0077" --password-stdin
  post_build:
    commands:
      # Take these images and push them to Docker hub
      - echo Pushing the Docker images...
      - docker push sohan0077/dkr-multicontainer-app-client
      - docker push sohan0077/dkr-multicontainer-app-backend
      - docker push sohan0077/dkr-multicontainer-app-nginx

artifacts:
  files:
    - "Dockerrun.aws.json"